"""empty message

Revision ID: 61ae783bce4f
Revises: 
Create Date: 2020-05-22 12:33:01.852718

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '61ae783bce4f'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('message', 'caption',
               existing_type=mysql.VARCHAR(length=255),
               nullable=True)
    op.alter_column('message', 'media_url',
               existing_type=mysql.VARCHAR(length=255),
               nullable=True)
    op.alter_column('message', 'text_message',
               existing_type=mysql.TEXT(),
               nullable=True)
    op.add_column('user', sa.Column('api_key', sa.String(length=255), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'api_key')
    op.alter_column('message', 'text_message',
               existing_type=mysql.TEXT(),
               nullable=False)
    op.alter_column('message', 'media_url',
               existing_type=mysql.VARCHAR(length=255),
               nullable=False)
    op.alter_column('message', 'caption',
               existing_type=mysql.VARCHAR(length=255),
               nullable=False)
    # ### end Alembic commands ###
